-- CREATE TABLE public.tb_data_monthly
-- (
--     id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
--     pisco double precision,
--     data double precision,
--     mes date,
--     "NOM_EST" text COLLATE pg_catalog."default",
--     "COD_EST" text COLLATE pg_catalog."default",
--     "COD_PISCO" bigint
-- )

-- TABLESPACE pg_default;

-- ALTER TABLE public.tb_data_monthly
--     OWNER to cnjihdpudzmxtp;

copy public.tb_data_monthly 
FROM 'E:/2020/pnud/webpage/geovisor/data.csv' 
DELIMITER ';' 
CSV HEADER
ESCAPE '''' FORCE NOT NULL id ;