# Generated by Django 2.2 on 2020-03-12 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_bh_historic',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_cuenca', models.TextField(blank=True, db_column='cod_cuenca', null=True)),
                ('nom_cuenca', models.TextField(blank=True, db_column='nom_cuenca', null=True)),
                ('anno', models.IntegerField(blank=True, db_column='anno', null=True)),
                ('pp', models.FloatField(blank=True, db_column='pp', null=True)),
                ('etp', models.FloatField(blank=True, db_column='etp', null=True)),
                ('etr', models.FloatField(blank=True, db_column='etr', null=True)),
                ('escurr', models.FloatField(blank=True, db_column='escurr', null=True)),
                ('caudal', models.FloatField(blank=True, db_column='caudal', null=True)),
            ],
            options={
                'db_table': 'tb_bh_historic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_bh_month',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_cuenca', models.TextField(blank=True, db_column='cod_cuenca', null=True)),
                ('nom_cuenca', models.TextField(blank=True, db_column='nom_cuenca', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='mes', null=True)),
                ('pp', models.FloatField(blank=True, db_column='pp', null=True)),
                ('etp', models.FloatField(blank=True, db_column='etp', null=True)),
                ('etr', models.FloatField(blank=True, db_column='etr', null=True)),
                ('escurr', models.FloatField(blank=True, db_column='escurr', null=True)),
                ('caudal', models.FloatField(blank=True, db_column='caudal', null=True)),
            ],
            options={
                'db_table': 'tb_bh_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_hydrogram_month',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_cuenca', models.TextField(blank=True, db_column='cod_cuenca', null=True)),
                ('nom_cuenca', models.TextField(blank=True, db_column='nom_cuenca', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='mes', null=True)),
                ('caudal', models.FloatField(blank=True, db_column='caudal', null=True)),
            ],
            options={
                'db_table': 'tb_hydrogram_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='data_hydrogram_year',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_cuenca', models.TextField(blank=True, db_column='cod_cuenca', null=True)),
                ('nom_cuenca', models.TextField(blank=True, db_column='nom_cuenca', null=True)),
                ('mes', models.DateTimeField(blank=True, db_column='mes', null=True)),
                ('caudal', models.FloatField(blank=True, db_column='caudal', null=True)),
            ],
            options={
                'db_table': 'tb_hydrogram_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='gpo_cuencas_tdps',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, db_column='codigo', null=True)),
                ('nombre', models.TextField(blank=True, db_column='nombre', null=True)),
                ('area', models.FloatField(blank=True, db_column='area_km2', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'gpo_cuencas_tdps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tb_stations_pp',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pisco', models.FloatField(blank=True, db_column='pisco', null=True)),
                ('data', models.FloatField(blank=True, db_column='data', null=True)),
                ('mes', models.DateField(blank=True, db_column='mes', null=True)),
                ('cod_est', models.TextField(blank=True, db_column='COD_EST', null=True)),
            ],
            options={
                'db_table': 'tb_data_monthly',
                'managed': False,
            },
        ),
    ]
