# Generated by Django 2.2 on 2020-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_data_monthly',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pisco', models.FloatField(blank=True, db_column='pisco', null=True)),
                ('data', models.FloatField(blank=True, db_column='data', null=True)),
                ('mes', models.DateField(blank=True, db_column='mes', null=True)),
                ('cod_est', models.TextField(blank=True, db_column='COD_EST', null=True)),
            ],
            options={
                'db_table': 'tb_data_monthly',
                'managed': False,
            },
        ),
    ]
