# Generated by Django 2.2 on 2020-03-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpo_cuencas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, db_column='codigo', null=True)),
                ('nombre', models.TextField(blank=True, db_column='nombre', null=True)),
                ('area', models.FloatField(blank=True, db_column='area_km2', null=True)),
            ],
            options={
                'db_table': 'gpo_cuencas_tdps',
                'managed': False,
            },
        ),
    ]
