# Generated by Django 2.2 on 2020-03-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_stations_pp',
        ),
    ]
