# Generated by Django 2.2 on 2020-04-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gpo_subcuencas_tdps'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_subcuencas_tdps_resultados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, db_column='codigo', null=True)),
                ('pp_month', models.TextField(blank=True, db_column='pp_month', null=True)),
                ('etp_month', models.TextField(blank=True, db_column='etp_month', null=True)),
                ('etr_month', models.TextField(blank=True, db_column='etr_month', null=True)),
                ('q_month', models.TextField(blank=True, db_column='q_month', null=True)),
                ('flow_out_month', models.TextField(blank=True, db_column='flow_out_month', null=True)),
            ],
            options={
                'db_table': 'tb_subcuencas_resultados',
                'managed': False,
            },
        ),
    ]
